apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - billytest.hopto.org
      secretName: letsencrypt-nginx
  rules:
    - host: billytest.hopto.org
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: starwars-service
                port:
                  number: 3000
